### ISSUE TITLE
Microk8s.io - build 

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/microk8s.io#25]
Using [the copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#) and [design](https://github.com/ubuntudesign/web-squad/issues/915) to build a demo

**Comment by inuwa** [comment]
From @anasereijo 

I reviewed the page with @Greggless and we have some things to change/to do.

#### DESIGN:
- [x] create and save grey background suru



#### DEV:
##### - nav changes
- [ ] set microk8s logo to `ubuntu light` 16px
- [ ] set microk8s logo `background-colour` to ubuntu orange (like we have on ubuntu.com)

##### - hero section assets (designs [here](https://github.com/ubuntudesign/web-squad/issues/915#issuecomment-440656460))
- [ ] background colour: `background: #F7F7F7;`
- [ ] [suru left](https://assets.ubuntu.com/v1/a413af31-suru+left.svg): apply `multiply`
- [ ] [suru right 1](https://assets.ubuntu.com/v1/78957c9e-suru+right+1.svg) apply `multiply`
- [ ] [suru right 2](https://assets.ubuntu.com/v1/c5e39473-suru+right+2.svg) apply `multiply`
- [ ] text col should be `class="col-8"`
- [ ] set `Get started with microk8s` button to be `class="p-button--positive"`
- [ ] [kubernetes certified logo](https://assets.ubuntu.com/v1/96d35aa4-certified-kubernetes-logo.svg): make it 179x241px
- [ ] [get if from the snap store logo](https://assets.ubuntu.com/v1/44a9abad-snap-store-badge-dark-en.svg): make it  179x54px
- [ ] vertical space between k8s logo and snapstore should be 16px


##### - other changes
- [ ] remove blue style from `p-list_item is-ticked` 
- [ ] set a scrolling animation `Get started buttons` 
- [ ] `code block` -  align code to the left side
- [ ] add footer from copy doc
- [ ] make sure it is responsive
