### ISSUE TITLE
Video on mobile viewports doesn't work and is way too large

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-websites/microk8s.io#34]
It's too big!

**Comment by anasereijo** [comment]
@Caleb-Ellis looks fine on mine! can you check if it's still happening on your phone?

![whatsapp image 2019-02-04 at 15 46 50](https://user-images.githubusercontent.com/36884067/52219249-29056100-2894-11e9-993f-c390e81ce560.jpeg)

**Comment by anasereijo** [comment]
@Caleb-Ellis, sorry, it's not displaying correctly on mine either! the viewport looks okay size wise but then it crops some text.
