### ISSUE TITLE
Why is 41 stroked out? Typo?

### ISSUE THREAD

**Issue by ktsakalozos** [canonical-websites/microk8s.io#49]
At the top the site reads:
"A single package of k8s that installs on 41 (stroked out)  42 flavours of Linux. Made for developers and great for appliances."

**Comment by Greggless** [comment]
Hi @ktsakalozos 

That's the copy Mark wanted. Please raise the issue in the copy doc and assign it to Mark.

I'll close this for now, but please re-open if we're to proceed with no ~~41~~ and just 42.

Thanks
