### ISSUE TITLE
Traefik not working

### ISSUE THREAD

**Issue by chngtrn** [canonical-websites/microk8s.io#63]
I installed Traefik in microk8s and able to access the Traefik dashboard and see all the ingresses frontends and backends but all of them gives me “Gateway timeout” error. I setup the exact same thing in minikube and it works fine. I installed Traefik into kube-system namespace with correct ClusterRole and ClusterRoleBinding. Is there something missing in microk8s that’s preventing Traefik to work? Any help is much appreciated. Thanks.

**Comment by anthonydillon** [comment]
@chngtrn thank you for the feedback. But, this issue list is for issues on the website. Could you please report your issue on the mircok8s project: https://github.com/ubuntu/microk8s/issues.
